pluginManagement {
    repositories {
        maven { url "https://artifactory.apps.bancolombia.com/maven-bancolombia" }
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'GgTournament'

include ':app-service'
include ':model'
include ':usecase'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
project(':usecase').projectDir = file('./domain/usecase')
include ':entry-point-test'
project(':entry-point-test').projectDir = file('./infrastructure/entry-points/entry-point-test')